version: 2
  jobs:
    swiftlinux:
      docker:
        - image: swift:4.1
      steps:
        - checkout
        - run: swift build
        - run: swift build -c release
        - run: swift test

workflows:
  version: 2
  build-swift:
    jobs:
      - swiftlinux

  nightly:
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - master

    jobs:
      - swiftlinux